In [15]:
import numpy as np

# Class

In [16]:
a = np.array([1, 2, 3]) # Create a rank 1 array
print(type(a))
# Prints "<class 'numpy.ndarray'>"
print(a.shape)
# Prints "(3,)"
print(a[0], a[1], a[2]) # Prints "1 2 3"
a[0] = 5
# Change an element of the array
print(a)
# Prints "[5, 2, 3]"
b = np.array([[1,2,3],[4,5,6]]) # Create a rank 2 array
print(b.shape)
# Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [17]:
a = np.zeros((2,2)) # Create an array of all zeros
print(a)
# Prints "[[ 0. 0.]
#          [ 0. 0.]]"

b = np.ones((1,2)) # Create an array of all ones
print(b)
# Prints "[[ 1. 1.]]"

c = np.full((2,2), 7) # Create a constant array
print(c)
# Prints "[[ 7. 7.]
#          [ 7. 7.]]"

d = np.eye(2)
print(d)
# Create a 2x2 identity matrix
# Prints "[[ 1. 0.]
#          [ 0. 1.]]"

e = np.random.random((2,2)) # Create an array filled with random values
print(e)
# Might print "[[ 0.91940167 0.08143941]
#               [ 0.68744134 0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.75358372 0.56371712]
 [0.73036294 0.44494942]]


In [18]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1 2 3 4]
#  [ 5 6 7 8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
# [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1]) # Prints "2"

b[0, 0] = 77 # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) # Prints "77"

[[2 3]
 [6 7]]
2
77


In [19]:
# [[ 1 2 3 4]
#  [ 5 6 7 8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :] # Rank 1 view of the second row of a
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
print(row_r1, row_r1.shape) # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape) # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]]) # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]])) # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]]) # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]])) # Prints "[2 2]"

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [22]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2) # Find the elements of a that are bigger than 2;
# this returns a numpy array of Booleans of the same
# shape as a, where each slot of bool_idx tells
# whether that element of a is > 2.
print(bool_idx)

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx]) # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2]) # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [23]:
x = np.array([1, 2]) # Let numpy choose the datatype
print(x.dtype)
# Prints "int64"
x = np.array([1.0, 2.0]) # Let numpy choose the datatype
print(x.dtype)
# Prints "float64"
x = np.array([1, 2], dtype=np.int64) # Force a particular datatype
print(x.dtype)
# Prints "int64"

int64
float64
int64


In [30]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0 8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.20.33333333]
#  [ 0.42857143 0.5]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.1.41421356]
#  [ 1.73205081 2.]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [33]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
# [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [34]:
x = np.array([[1,2],[3,4]])
print(np.sum(x)) # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0)) # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1)) # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [36]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v) # Prints "[1 2 3]"
print(v.T) # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


In [39]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x) # Create an empty matrix with the same shape as x
# Add the vector v to each row of the matrix x with an explicit loop

for i in range(4):
    y[i, :] = x[i, :] + v
    
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [41]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1)) # Stack 4 copies of v on top of each other
print(vv)

y = x + vv # Add x and vv elementwise
print(y)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [42]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [65]:
# Compute outer product of vectors
v = np.array([1,2,3]) # v has shape (3,)
w = np.array([4,5]) # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4 5]
# [ 8 10]
# [12 15]]
print(np.reshape(v, (3, 1)) * w)
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
# [5 7 9]]
print(x + v)
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5 6 7]
# [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2 4 6]
# [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


# Tasks

1) Створіть 1D масив чисел від 0 до 9

In [4]:
arr = np.array([i for i in range(10)])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2) Створіть 3×3 numpy масив, що складається с усіх True’s

In [6]:
arr = np.full((3, 3), True)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3) Отримайте всі непарні числа з масиву

In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
output = arr[arr % 2 == 1]
output

array([1, 3, 5, 7, 9])

4) Треба замінити всі непарні числа на -1

In [54]:
#

5) Треба замінити всі непарні числа на -1 не змінюючі масив (where)

In [56]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr % 2 == 1, -1, arr)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

6) Перетворіть 1D масив у 2D масив з 2 рядками (reshape)

In [72]:
arr = np.arange(10)
print(arr)
print(arr.reshape((2, 5)))
print(arr.reshape(2,-1))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


7) Складіть вертикально масиви a та b (функції vstack, hstack, concatenate)

In [75]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

8) Складіть горизонтально два масиви

In [84]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a, b), axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9) Зробіть наступний патерн не використовуючи жорстке прописування коду.

Використовуйте тільки функції numpy (використовуйте функцію tile)

In [102]:
a = np.array([1,2,3])

a1 = np.tile(a, (a.shape[0], 1)).T.reshape(9,)
a2 = np.tile(a, a.shape[0])

output = np.concatenate((a1, a2))
output

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

10) Отримайте однакові значення між масивами a and b (можете використати функцію intersect1d)

In [104]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a, b)

array([2, 4])

11) З масиву a відилать значення, які є у масиві b (функція setdiff1d)

In [107]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

12) Отримайте індекси елементів які співпадають у двох масивах (where)

In [109]:
a = np.array([1, 2, 3,  2, 3,4,3,4,5,6])
b = np.array([7, 2, 10, 2, 7,4,9,4,9,8])

np.where((a==b))

(array([1, 3, 5, 7]),)

13) Отримайте всі значення які більші за 5 та менші або рівні 10 (where, logical_and).

In [124]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
mask = np.where(np.logical_and((a > 5), (a <= 10)))
a[mask]

array([ 6,  9, 10])

14) Перетворіть функцію maxx яка працює з двома скалярними значеннями так, 

щоб вона могла працювати з масивами (vectorize(maxx, otypes=[float]))

In [136]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
    
def pair_max(x, y):
    return np.column_stack((x, y)).max(1)
    
    
# maxx(1, 5)
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)

array([6, 7, 9, 8, 9, 7, 5])

15) Поміняйте місцями колонку 1 та 2

In [154]:
arr = np.arange(9).reshape(3,3)
output = arr.copy()
output[:, 1] = arr[:, 2]
output[:, 2] = arr[:, 1]
output

array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

16) Створіть 2D масив розміром 5x3 який складається з довільних десяткових
чисел у діапазоні між 5 та 10.

In [161]:
arr = np.random.randint(5, 10, size=(2, 4))
arr

array([[7, 6, 6, 5],
       [9, 8, 6, 7]])

17) Як виводити тільки 3 знаки після коми в масиві numpy (set_printoptions(precision=))

In [176]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.67 , 0.576, 0.554],
       [0.371, 0.573, 0.858],
       [0.043, 0.856, 0.747],
       [0.685, 0.504, 0.514],
       [0.704, 0.229, 0.25 ]])

18) Як друкувати масив змінивши наукову нотацію на інженерну (1e-01 –> 0.1) 
(set_printoptions(suppress = , precision=))

In [182]:
rand_arr = np.random.random((5,3)) / 10000
np.set_printoptions(precision=3, suppress=True)
rand_arr 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

19) Як надрукувати весь масив numpy без обрізання значень (set_printoptions(threshold =))

In [183]:
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

20) Імпортуйте датасет iris зберігаючи текст неушкодженим

In [184]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

21) Отримайте текс за колонки species ([row[4] for row in iris_1d])

In [195]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = [row[4] for row in iris_1d]

/home/sashatr/Desktop/projects/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


22) Змініть 1D iris на 2D масив iris_2d опустивши текстове поле species
([row.tolist()[:4] for row in iris_1d]).

In [196]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
without_species = [row.tolist()[:4] for row in iris_1d]

/home/sashatr/Desktop/projects/venv/lib/python3.6/site-packages/ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


23) Знайдіть mean, median, standard deviation першої колонки sepallength
(genfromtxt(usecols=))

In [225]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.array([row[0] for row in iris_1d])

print('Mean:', np.mean(sepallength))
print('Median:', np.median(sepallength))
print('Standard deviation:', np.std(sepallength))

ptp = np.ptp(sepallength)
print("ptp:", ptp)

Mean: 5.843333333333334
Median: 5.8
Standard deviation: 0.8253012917851409
ptp: 3.6000000000000005


24) Створіть нормалізовану форму з iris 's sepallength із значеннями між 0 та 1
так що мінімальне значення буде 0 а максимальне 1 (numpy.ptp).

In [226]:
# sepallength_norm = 
max_ = sepallength.max()
min_ =sepallength.min()
sepallength = list(sepallength)
sepallength_norm = [round(((item - min_)/round(ptp, 2)), 2) for item in sepallength]

25) Розрахуйте 5th та 95th перцентилі iris's sepallength

In [229]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(np.percentile(sepallength, 5))
print(np.percentile(sepallength, 95))

4.6
7.254999999999998


26) Знайдіть позиції пропущених значень в першій колонці (where, isnan) iris_2d 's sepallength

In [240]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

idxs = np.where(np.isnan(iris_2d))
idxs

(array([  0,   1,   2, ..., 147, 148, 149]), array([4, 4, 4, ..., 4, 4, 4]))

27) Виберіть рядки iris_2d датасету які не мають nan значень
([~np.any(np.isnan(row) for row in iris_2d)]).

28) Find the correlation between SepalLength(1st column) and PetalLength(3rd column) in iris_2d

29) Розрахуйте евклідові відстані між двома масивами (linalg.norm).

30) Знайдіть всі піки в 1D numpy масиві a . Піки це точки з двох боків які
мають менших сусідів (diff, where, sign).