# Основи роботи у Pytorch.

In [47]:
import torch
import numpy as np

1. Створіть із списку тензор з list(range(9)). Передбачте та перевірте, який розмір, зсув та кроки він має.<br>
*storage_offset + stride [0] * i + stride [1] * j*

In [17]:
a = torch.tensor(list(range(9)))
a

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
a.storage()

 0
 1
 2
 3
 4
 5
 6
 7
 8
[torch.LongStorage of size 9]

In [19]:
a.storage_offset()

0

In [20]:
a.size()

torch.Size([9])

In [21]:
a.stride()

(1,)

2. Створіть тензор b = a.view(3, 3). Яке значення має b[1,1]?

In [23]:
b = a.view(3, 3)
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [24]:
b[1][1]

tensor(4)

3. Створіть тензор c = b[1:,1:]. Передбачте та перевірте, який розмір, зсув та кроки.

In [37]:
print(b)

print(b.size())
print(b.storage_offset())
print(b.stride())

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
torch.Size([3, 3])
0
(3, 1)


In [38]:
c = b[1:, 1:]

In [40]:
print(c)

print(c.size())
print(c.storage_offset())
print(c.stride())

tensor([[4, 5],
        [7, 8]])
torch.Size([2, 2])
4
(3, 1)


4. Виберіть математичну операцію, як косинус або квадратний корінь.<br>
Чи можете ви знайти відповідну функцію в бібліотеці torch?

In [62]:
a = torch.from_numpy(np.array([1, 2, 3], dtype='float64'))
a

tensor([1., 2., 3.], dtype=torch.float64)

In [63]:
d = torch.cos(a) 
d

tensor([ 0.5403, -0.4161, -0.9900], dtype=torch.float64)

5. Чи існує версія вашої функції, яка працює in-place?

In [65]:
d.cos_()

tensor([0.8576, 0.9147, 0.5487], dtype=torch.float64)